### ISSUE TITLE
Unauthorised when making rpc calls

### ISSUE THREAD

**Issue by DeathEaterLN** [vergecurrency/nodejs-verge#18]
Hi, I'm trying to do a simple rpc call on my verge node using nodejs script. I have setup all the necessary authentication and config files. But I still get the following error: 

Error: Invalid params 401 : "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n\"http://www.w3.org/TR/1999/REC-html401-19991224/loose.dtd\">\r\n<HTML>\r\n<HEAD>\r\n<TITLE>Error</TITLE>\r\n<META HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=ISO-8859-1'>\r\n</HEAD>\r\n<BODY><H1>401 Unauthorized.</H1></BODY>\r\n</HTML>\r\n"
3|api  |     at IncomingMessage.<anonymous> (/plaak/blockchain-api/node_modules/node-verge/lib/verge.js:82:31)
3|api  |     at emitNone (events.js:111:20)
3|api  |     at IncomingMessage.emit (events.js:208:7)
3|api  |     at endReadableNT (_stream_readable.js:1064:12)
3|api  |     at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
3|api  |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
3|api  |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

I'm running this : 

let XVGStatus = await verge.getDifficulty(function (error, result) {
        if (error) {
            console.log(error);
        }

        else {
            console.log(result);
        }
    })

**Comment by marpme** [comment]
how did you initialize the `verge` variable? 
is you node running on the same system as you run your verge script right now?

**Comment by DeathEaterLN** [comment]
the verge variable is exported from a config file.


verge = require('node-verge')()
verge.auth('user', 'pass')
module.exports = verge;

It worked when I setup my node in local machine (Windows) but when running on a ubuntu server. It doesn't seem to give me access. Any ideas?

The code and VERGE.conf file are literally the same. And yes, I'm running the script on the same system as my node. :)

**Comment by DeathEaterLN** [comment]
My bad. My password has a # at the end of it and didnt realise that shell scripts dont recognise them. Closing the issue, thanks for your help.

**Comment by marpme** [comment]
Glad you figured that out and posted the solution over here 👍
